# Generated by Django 4.2.2 on 2023-06-30 07:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChemicalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("product_url", models.URLField(max_length=1024)),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("availability", models.BooleanField()),
                ("numcas", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                (
                    "qt_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=5
                    ),
                ),
                (
                    "unit_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("mg", "Milligram"),
                                ("g", "Gram"),
                                ("kg", "Kilogram"),
                                ("pack", "Pack"),
                                ("ml", "Milliliter"),
                                ("l", "Liter"),
                            ],
                            max_length=8,
                        ),
                        size=5,
                    ),
                ),
                (
                    "currency_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), size=5
                    ),
                ),
                (
                    "price_pack_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Chemical Product",
                "verbose_name_plural": "Chemical Products",
            },
        ),
    ]
