# Generated by Django 4.2.2 on 2023-06-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parsers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemicalproduct",
            name="numcas",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
