services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --reload chemical_parser.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4"
    volumes:
        - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:alpine
    restart: unless-stopped


  celery:
    build:
      context: .
    command: "celery -A chemical_parser worker --loglevel=info --concurrency 1 -E"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
      - app
      - db

  scrapyd:
    build:
      context: .
    command: "scrapyd"
    ports:
      - "6800:6800"
    restart: unless-stopped
    depends_on:
      - redis
      - app
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5555:5555"
    command: "celery -A chemical_parser flower --address=0.0.0.0"
    depends_on:
      - celery
    env_file:
      - .env

  splash:
    image: scrapinghub/splash:latest
    restart: unless-stopped
    ports:
      - "8050:8050"
    depends_on:
      - scrapyd

volumes:
    static_volume: {}
    postgres_data: {}
